### PR TITLE
Add CTTAP to list of Erlang TAP producers

### PR DESCRIPTION
**Pull request by Stratus3D**
CTTAP is a new TAP producer that integrates with Erlang's existing testing framework (Common Test).

### CODE REVIEW

**Comment by mblayman** [comment]
@Stratus3D Thanks for the contribution! A few quick comments.

1. All the tools are alphabetized in each language section. This was a bit hard to tell because Erlang only had one entry. Could you please move this above the `etap` entry?
2. The first sentence is missing an article. `is Common Test hook` => `is a Commont Test hook`
3. GitHub serves traffic over HTTPS. Can you update the url to use `https`?

**Comment by Stratus3D** [comment]
Updated the PR with those corrections. I also updated the etap URL to use HTTPS as well.

**Comment by mblayman** [comment]
:+1: Looks great, thanks!

**Comment by jonathanKingston** [comment]
:+1: thanks

**Pull request merged**
