### PR TITLE
Add tapto consumer.

### PR DESCRIPTION
**Pull request by katef**
Just adding my own thing to the list. It's written in C, so I added it to the C section.
It outputs to XML, and uses XSLT to render that to HTML and whatever else.

### CODE REVIEW

**Comment by mblayman** [comment]
@katef Thanks for the contribution! The tools listed on the consumers and producers do not include an author. This is often because the projects are a collaboration of many people, but I know first-hand from reviewing many of them that they can be solo efforts. I'm happy to merge if you can change the HTML link text to `tapto tool` or `tapto`. Thanks!

**Comment by katef** [comment]
@mblayman Can do, sure. Perhaps stupidly, I gave my tool such a generic name that I thought it's entirely possible that somebody else might have named theirs the same.

**Comment by mblayman** [comment]
LGTM

**Comment by katef** [comment]
Thank you!

**Pull request merged**
