### PR TITLE
Move the nonproliferation treaty to the TAP history.

### LINKED ISSUE #59: Discuss removal of Non Proliferation comments
>Non Proliferation
TAP producer authors should be aware of (and hopefully sign) the TAP Namespace Nonproliferation Treaty

These comments in the pages have existed for a long time.

I would like to remove them because:
- I don't think it helps making TAP a usable format across other languages
- I don't think it actually helps solve any issue
- I think it makes the TAP community look closed and require a license somewhat

Discuss!

### PR DESCRIPTION
**Pull request by mblayman**
This should help reduce confusion while respecting that the Perl community may still abide by this treaty.

Fixes #59

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Requires more discussion in #59 despite being the status quo.

**Comment by mblayman** [comment]
@jonathanKingston I take the silence on issue #59 for nearly three months as an indicator that folks either don't care or are ok with removing the nonproliferation stuff. What do you think about moving forward with this PR?

**Comment by mblayman** [comment]
@jonathanKingston I merged master on this one which resolved the conflicts and pulled in the linkified section headers.

**Comment by jonathanKingston** [comment]
:+1: thanks!

**Pull request merged**
