### PR TITLE
Added painless to JS producer list

### PR DESCRIPTION
**Pull request by taylorhakes**
[Painless](https://github.com/taylorhakes/painless) test library supports TAP. This adds it to the producer list.

### CODE REVIEW

**Comment by mblayman** [comment]
@taylorhakes The tools are alphabetically sorted. Could you please move this to be after Mocha?

**Comment by mblayman** [comment]
Uh, I guess I should learn the alphabet. :blush: I should have said after `node-tap`.

**Comment by taylorhakes** [comment]
done

**Comment by mblayman** [comment]
:+1: Thanks!

**Pull request merged**
