### PR TITLE
Adding in AVA now that it has a TAP producer

### PR DESCRIPTION
**Pull request by jonathanKingston**

### CODE REVIEW

**Comment by mblayman** [comment]
This branch has conflicts. The JavaScript section was updated so this current branch does not match the new styling. Once it's updated to remove conflicts and match the style of the other stuff, I'll be happy to give my thumbs up.

**Comment by jonathanKingston** [comment]
Heh yeah super old branch, I knew something looked bad. Now has been rebased.

**Comment by mblayman** [comment]
:+1:

**Comment by jonathanKingston** [comment]
@mblayman thanks for the review!

**Pull request merged**
