### PR TITLE
Update default.html

### PR DESCRIPTION
**Pull request by Shubhajit-Paul**
adding underline in navigation

### CODE REVIEW

**Comment by mblayman** [comment]
I'm not opposed to adding underlines to those links. Since that's a design style change, could you change the CSS `extra` class that those links use instead of adding markup to the HTML?

**Comment by Shubhajit-Paul** [comment]
I will try

**Review by Krinkle — CHANGES_REQUESTED** [review]
Per previous comments.

**Comment by mblayman** [comment]
I'm pretty sure this was Hacktoberfest shenanigans, and the contributor disappeared with making the requested edits. I'm closing this.

**Pull request closed without merging**
