### PR TITLE
Add Fish and Fishtape

### PR DESCRIPTION
**Pull request by bucaran**
Hi, my bad for opening a new PR. I was lazy and originally cloned and committed directly from GitHub because I thought it was just a simple entry addition :sweat_smile: 

I have addressed the issue you brought up in https://github.com/TestAnything/testanything.github.io/pull/43

Let me know if there are other areas you would like me to help, website, etc.

### CODE REVIEW

**Comment by mblayman** [comment]
Awesome, thanks for going above and beyond! :+1:

**Comment by mblayman** [comment]
@bucaran Looks like there is now a small merge conflict. I'd push up the commit that would eliminate the conflict and merge your work without troubling you, but I don't have write access to the repo to do that.

**Comment by bucaran** [comment]
No prob. Rebased.

**Comment by mblayman** [comment]
One final thing and I think it will be finished. In the rebase, the Forth anchor tag and the Forth header were separated by the Fish entry. Could you move the Forth anchor back to being directly above the Forth header?

**Comment by bucaran** [comment]
@mblayman My bad, fixed.

**Comment by mblayman** [comment]
Looks good to me. :+1: /cc @jonathanKingston

**Comment by mblayman** [comment]
@jonathanKingston could you merge this one when you get a chance? I'd like to work on the Erlang and Forth sections, but I don't want to create more merge conflicts for @bucaran.

**Comment by jonathanKingston** [comment]
:+1: @bucaran 
Thanks again @mblayman; just have seen the broken Forth section also.

**Pull request merged**
