### PR TITLE
Update producers.md to include Fortran

### PR DESCRIPTION
**Pull request by dennisdjensen**
Added a paragraph about fortran-testanything for the programming language Fortran and a link to it at the top.

### CODE REVIEW

**Comment by mblayman** [comment]
@dennisdjensen, thanks! This looks good to me. Do you have a link to `fortran-testanything`? It looks like you planned to have a link, but the parentheses are empty. I'll be happy to merge once the link is added.

**Comment by dennisdjensen** [comment]
@mblayman, oopsie daisy. I put in a link: https://github.com/dennisdjensen/fortran-testanything.

**Comment by mblayman** [comment]
Great, thank you!

**Comment by mblayman** [comment]
👍

**Pull request merged**
